services:
  #### FEDOW ####
  fedow_django:
    volumes:
      - ./backup:/backup_tdd
    extends:
      file: ../Fedow/docker-compose.yml
      service: fedow_django
    command: 'bash start_dev.sh'
    extra_hosts:
      - "fedow.tibillet.localhost:172.17.0.1"
      - "lespass.tibillet.localhost:172.17.0.1"
      - "laboutik.tibillet.localhost:172.17.0.1"
      # For mock data :
      - "fedow.tibillet.coop:172.17.0.1"
      - "raffinerie.tibillet.re:172.17.0.1"
      - "raffinerie.cashless.tibillet.re:172.17.0.1"

  fedow_memcached:
    extends:
      file: ../Fedow/docker-compose.yml
      service: fedow_memcached

  fedow_nginx:
    extends:
      file: ../Fedow/docker-compose.yml
      service: fedow_nginx
    labels:
      - traefik.http.routers.fedow_nginx.rule=Host(`fedow.$DOMAIN`)

  #### LESPASS ####

  lespass_postgres:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_postgres

  lespass_memcached:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_memcached

  lespass_redis:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_redis

  lespass_django:
    volumes:
      - ./backup:/backup_tdd
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_django
    extra_hosts:
      - "fedow.tibillet.localhost:172.17.0.1"
      - "lespass.tibillet.localhost:172.17.0.1"
      - "laboutik.tibillet.localhost:172.17.0.1"
      # For mock data :
      - "fedow.tibillet.coop:172.17.0.1"
      - "raffinerie.tibillet.re:172.17.0.1"
      - "raffinerie.cashless.tibillet.re:172.17.0.1"
    command: 'bash start_dev.sh'

  lespass_celery:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_celery
    command: "poetry run celery -A TiBillet worker -l INFO"
  #    command: 'bash start_dev.sh'

  lespass_nginx:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_nginx
    labels:
      - traefik.http.routers.lespass_nginx.rule=Host(`$DOMAIN`) || Host(`www.$DOMAIN`) || Host(`agenda.$DOMAIN`) || Host(`lespass.$DOMAIN`) || Host(`demo.$DOMAIN`)

  #### CASHLESS 1 ####

  laboutik_postgres:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_postgres

  laboutik_memcached:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_memcached

  laboutik_redis:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_redis

  laboutik_django:
    volumes:
      - ./backup:/backup_tdd
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_django
    command: 'bash start_dev.sh'
    extra_hosts:
      - "fedow.tibillet.localhost:172.17.0.1"
      - "lespass.tibillet.localhost:172.17.0.1"
      - "laboutik.tibillet.localhost:172.17.0.1"
      # For mock data :
      - "fedow.tibillet.coop:172.17.0.1"
      - "raffinerie.tibillet.re:172.17.0.1"
      - "raffinerie.cashless.tibillet.re:172.17.0.1"
  laboutik_celery:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_celery
  #    command: 'bash start_dev.sh'

  laboutik_nginx:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_nginx
    labels:
      - traefik.http.routers.laboutik_nginx.rule=Host(`laboutik.$DOMAIN`) || Host(`cashless.$DOMAIN`)

  ### Playwright test container
  playwright:
    build: playwright/PlaywrightDockerFile
    container_name: playwright
    hostname: playwright
    network_mode: host
    volumes:
      - ./playwright:/playwright
    tty: true
    command: "/bin/bash"
    extra_hosts:
      - "fedow.tibillet.localhost:172.17.0.1"
      - "lespass.tibillet.localhost:172.17.0.1"
      - "laboutik.tibillet.localhost:172.17.0.1"

networks:
  frontend:
    external: true
  fedow_backend:
  lespass_backend:
  laboutik_backend:

volumes:
  lespass_dev_db:
  laboutik_postgres_data:
  fedow_database:
