services:
  ### TRAEFIK PROXY ####
  traefik:
    image: "traefik:beaufort"
    container_name: "traefik"
    hostname: "traefik"
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.network=frontend"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.entrypoints-https.address=:443"
      - "--entrypoints.entrypoints-http.address=:80"
      - "--entrypoints.entrypoints-http.http.redirections.entryPoint.to=entrypoints-https"
      - "--entrypoints.entrypoints-http.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    networks:
      - frontend
    depends_on:
      - laboutik_nginx
      - fedow_nginx
      - lespass_nginx

  #### FEDOW ####
  fedow_django:
    volumes:
      - ./backup:/backup_tdd
    extends:
      file: ../Fedow/docker-compose.yml
      service: fedow_django
    command: 'bash start_dev.sh'
    extra_hosts:
      - fedow.tibillet.localhost:172.17.0.1
      - lespass.tibillet.localhost:172.17.0.1
      - laboutik.tibillet.localhost:172.17.0.1
    ports:
      - 8442:8000 # test stripe listen --forward-to http://127.0.0.1:8442/webhook_stripe/

  fedow_memcached:
    extends:
      file: ../Fedow/docker-compose.yml
      service: fedow_memcached

  fedow_nginx:
    depends_on:
      - fedow_django
    extends:
      file: ../Fedow/docker-compose.yml
      service: fedow_nginx
    labels:
      - traefik.http.routers.fedow_nginx.rule=Host(`fedow.$DOMAIN`)

  #### LESPASS ####

  lespass_postgres:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_postgres

  lespass_memcached:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_memcached

  lespass_redis:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_redis

  lespass_django:
    volumes:
      - ./backup:/backup_tdd
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_django
    extra_hosts:
      - fedow.tibillet.localhost:172.17.0.1
      - lespass.tibillet.localhost:172.17.0.1
      - laboutik.tibillet.localhost:172.17.0.1

    command: 'bash start_dev.sh'

  lespass_celery:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_celery
    command: "poetry run celery -A TiBillet worker -l INFO -B"
#    command: 'bash start_dev.sh'
    extra_hosts:
      - "fedow.tibillet.localhost:172.17.0.1"
      - "lespass.tibillet.localhost:172.17.0.1"
      - "laboutik.tibillet.localhost:172.17.0.1"
#      - "laboutik2.tibillet.localhost:172.17.0.1"

  lespass_nginx:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_nginx
    labels:
      - traefik.http.routers.lespass_nginx.rule=Host(`$DOMAIN`) || Host(`www.$DOMAIN`) || Host(`agenda.$DOMAIN`) || Host(`lespass.$DOMAIN`) || Host(`linterupteur.$DOMAIN`) || Host(`demo.$DOMAIN`) || Host(`bis.domainbis.localhost`) || Host(`domainbis.localhost`)
    depends_on:
      - lespass_django

  #### CASHLESS 1 ####

  laboutik_postgres:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_postgres

  laboutik_memcached:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_memcached

  laboutik_redis:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_redis

  laboutik_django:
    volumes:
      - ./backup:/backup_tdd
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_django
    ports:
      - 8000:8000
    command: 'bash start_dev.sh'
    extra_hosts:
      - fedow.tibillet.localhost:172.17.0.1
      - lespass.tibillet.localhost:172.17.0.1
      - laboutik.tibillet.localhost:172.17.0.1

  laboutik_celery:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_celery
#    command: 'bash start_dev.sh'
    command: 'bash start_celery.sh'
    extra_hosts:
      - fedow.tibillet.localhost:172.17.0.1
      - lespass.tibillet.localhost:172.17.0.1
      - laboutik.tibillet.localhost:172.17.0.1

  laboutik_nginx:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_nginx
    labels:
      - traefik.http.routers.laboutik_nginx.rule=Host(`laboutik.$DOMAIN`) || Host(`cashless.$DOMAIN`)
    depends_on:
      - laboutik_django


  #### CASHLESS 2 ####
#
#  laboutik2_postgres:
#    env_file: ../LaBoutik/env_test2
#    hostname: laboutik2_postgres
#    container_name: laboutik2_postgres
#    volumes:
#      - laboutik_postgres2_data:/var/lib/postgresql/data
#    extends:
#      file: ../LaBoutik/docker-compose.yml
#      service: laboutik_postgres
#
#  laboutik2_memcached:
#    hostname: laboutik2_memcached
#    container_name: laboutik2_memcached
#    extends:
#      file: ../LaBoutik/docker-compose.yml
#      service: laboutik_memcached
#
#  laboutik2_redis:
#    hostname: laboutik2_redis
#    container_name: laboutik2_redis
#    extends:
#      file: ../LaBoutik/docker-compose.yml
#      service: laboutik_redis
#
#  laboutik2_django:
#    hostname: laboutik2_django
#    container_name: laboutik2_django
#    volumes:
#      - ./backup:/backup_tdd
#    extends:
#      file: ../LaBoutik/docker-compose.yml
#      service: laboutik_django
#    env_file: ../LaBoutik/env_test2
#    links:
#      - laboutik2_postgres:postgres
#      - laboutik2_redis:redis
#      - laboutik2_memcached:memcached
#    extra_hosts:
#      - "fedow.tibillet.localhost:172.17.0.1"
#      - "lespass.tibillet.localhost:172.17.0.1"
#      - "laboutik.tibillet.localhost:172.17.0.1"
#      - "laboutik2.tibillet.localhost:172.17.0.1"
#    command: 'bash start_dev.sh'
#
#  laboutik2_celery:
#    hostname: laboutik2_celery
#    container_name: laboutik2_celery
#    extends:
#      file: ../LaBoutik/docker-compose.yml
#      service: laboutik_celery
#    env_file: ../LaBoutik/env_test2
#    links:
#      - laboutik2_postgres:postgres
#      - laboutik2_redis:redis
#      - laboutik2_memcached:memcached
#    extra_hosts:
#      - "fedow.tibillet.localhost:172.17.0.1"
#      - "lespass.tibillet.localhost:172.17.0.1"
#      - "laboutik.tibillet.localhost:172.17.0.1"
#      - "laboutik2.tibillet.localhost:172.17.0.1"
##    command: 'bash start_dev.sh'
#
#  laboutik2_nginx:
#    hostname: laboutik2_nginx
#    container_name: laboutik2_nginx
#    extends:
#      file: ../LaBoutik/docker-compose.yml
#      service: laboutik_nginx
#    links:
#      - laboutik2_django:laboutik_django
#    labels:
#      - traefik.http.routers.laboutik2_nginx.rule=Host(`laboutik2.$DOMAIN`)

  ### Playwright test container
  playwright:
    hostname: playwright
    container_name: playwright
    build: playwright/PlaywrightDockerFile
    network_mode: host
    volumes:
      - ./playwright:/playwright
    tty: true
    command: "/bin/bash"
    extra_hosts:
      - fedow.tibillet.localhost:172.17.0.1
      - lespass.tibillet.localhost:172.17.0.1
      - laboutik.tibillet.localhost:172.17.0.1

# Pour test stripe :
# stripe listen --forward-to https://fedow.tibillet.localhost/webhook_stripe/ --skip-verify

networks:
  frontend:
    external: true
  fedow_backend:
  lespass_backend:
  laboutik_backend:

volumes:
  lespass_dev_db:
  laboutik_postgres_data:
  laboutik_postgres2_data:
  fedow_database:
