services:
  #### FEDOW ####
  fedow_django:
    extends:
      file: ../Fedow/docker-compose.yml
      service: fedow_django
    command: 'bash start_dev.sh'

  fedow_memcached:
    extends:
      file: ../Fedow/docker-compose.yml
      service: fedow_memcached

  fedow_nginx:
    extends:
      file: ../Fedow/docker-compose.yml
      service: fedow_nginx
    labels:
      - traefik.http.routers.fedow_nginx.rule=Host(`fedow.$DOMAIN`)

  #### LESPASS ####

  lespass_postgres:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_postgres

  lespas_memcached:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespas_memcached

  lespas_redis:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespas_redis

  lespass_django:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_django
    command: 'bash start_dev.sh'

  lespass_celery:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_celery
#    command: "poetry run celery -A TiBillet worker -l INFO"
    command: 'bash start_dev.sh'

  lespass_nginx:
    extends:
      file: ../Lespass/docker-compose.yml
      service: lespass_nginx
    labels:
      - traefik.http.routers.lespass_nginx.rule=Host(`$DOMAIN`) || Host(`www.$DOMAIN`) || Host(`agenda.$DOMAIN`) || Host(`demo.$DOMAIN`) || Host(`billetistan.$DOMAIN`)

  #### CASHLESS 1 ####

  laboutik_postgres:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_postgres

  laboutik_redis:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_redis

  laboutik_django:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_django
    command: 'bash start_dev.sh'

  laboutik_celery:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_celery
#    command: 'bash start_dev.sh'

  laboutik_nginx:
    extends:
      file: ../LaBoutik/docker-compose.yml
      service: laboutik_nginx
    labels:
      - traefik.http.routers.laboutik_nginx.rule=Host(`cashless.$DOMAIN`)

networks:
  frontend:
    external: true
  fedow_backend:
  lespass_backend:
  laboutik_backend:

volumes:
  lespass_dev_db:
  laboutik_postgres_data:
  fedow_database: