#!/bin/bash

SESSION_NAME="F_Testing"

# Check if the session already exists
if tmux has-session -t $SESSION_NAME 2>/dev/null; then
    echo "Session $SESSION_NAME already exists. Attaching to it."
    byobu attach -t "$SESSION_NAME"
else
    # Create a new session and name it
    byobu new-session -d -s "$SESSION_NAME"

    # terminal
    byobu select-pane -t 0
    byobu send-keys "clear" Enter
    byobu send-keys "cd /media/travail/developpement/gits/Test-Driven-Development/" Enter
    byobu send-keys "docker compose down -v --remove-orphans && docker compose up -d && docker compose logs -f" Enter

    # 2 terminaux
    byobu split-window -v
    byobu split-window -v
    byobu split-window -v

    byobu select-pane -t 1
    byobu send-keys "dexe fedow_django bash"

    byobu select-pane -t 2
    byobu send-keys "dexe lespass_django bash"

    byobu select-pane -t 3
    byobu send-keys "dexe laboutik_django bash"

    byobu attach -t "$SESSION_NAME"

fi
