#!/bin/bash
# $@ = The value of all the arguments passed to the script.
argument=("$@")

all_tests () {
  echo "Lancement tests laboutik :"
  docker exec -ti playwright /bin/bash -c "npx playwright test tests/laboutik/"
}

tests () {
  docker exec -ti playwright /bin/bash -c "npx playwright test $1"
}

# le dossier ./playwright/node_modules n'existe pas
if [ ! -d "./playwright/node_modules" ]; then
  echo "Installation de playwrigh :"
  docker exec -ti playwright /bin/bash -c "npm i"
fi

# le premier argument existe
if [ -n "${argument[0]}" ]; then
tests
else
all_tests
fi
