#!/bin/bash
echo "launch laboutik"

docker exec -it laboutik_django /bin/bash -c "./flush.sh" | while read line; do
  echo $line
  # le premier argument existe
  argument=("$@")
  if [ -n "${argument[0]}" ]; then
    if [[ $line == *"Quit the server with CONTROL-C."* ]]; then 
      gnome-terminal -- bash -c "./dev_environment_auto/launch_tests; exec bash"
    fi
  fi
done
