#!/bin/bash
cd ../../TraefikV3/
docker compose down -v --remove-orphans && docker compose up -d 
cd ../Test-Driven-Development/demo/
docker compose down -v --remove-orphans && docker compose up -d
docker compose logs -f | while read line; do
  # Process the line here
  echo $line
  if [[ $line == *"INFO celery@lespass_celery ready."* ]]; then 
    tmux send-keys -t 1 "../dev_environment_auto/launch_fedow" Enter
  fi
done 
