#!/bin/bash
tmux kill-server
SESSION_NAME="TEST-DRIVEN"
ROOT_PATH="../"

if tmux has-session -t $SESSION_NAME 2>/dev/null; then
    echo "Session $SESSION_NAME already exists. Attaching to it."
    byobu attach -t "$SESSION_NAME"
else
    byobu new-session -d -s 'test'
    byobu rename-window -t 'test':0 $SESSION_NAME

    # 3 terminaux
    byobu split-window -v
    byobu split-window -v
    byobu split-window -v

    # lancement containers et logs
    byobu select-pane -t 0
    # byobu send-keys "cd $ROOT_PATH" Enter
    byobu send-keys "./launch_containers" Enter

    # lancement fedow
    byobu select-pane -t 1
    # byobu send-keys "cd $ROOT_PATH" Enter

    # lancement lespass
    byobu select-pane -t 2
    # byobu send-keys "cd $ROOT_PATH" Enter

    # lancement laboutik
    byobu select-pane -t 3
    # byobu send-keys "cd $ROOT_PATH" Enter


    # visualiser la session byobu dans la console
    byobu attach-session -t "test"
fi
