#https://www.baeldung.com/linux/docker-container-gui-applications
services:
  playwright:
    build: PlaywrightDockerFile
    container_name: playwright
    hostname: playwright
    network_mode: host
    volumes:
      - ./:/playwright
    tty: true
    command: "/bin/bash"