#https://www.baeldung.com/linux/docker-container-gui-applications
services:
  playwright:
    build: PlaywrightDockerFile
    container_name: playwright
    environment:
        - DISPLAY=${DISPLAY}
    network_mode: host
    privileged: true
    volumes:
      - ./tests:/home/docker_user/Playwright/tests
      - ./mesModules:/home/docker_user/Playwright/mesModules
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    command: "/bin/bash"
